apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .Values.persistentvolumeclaim.name }} 
  namespace: foundry 
spec: 
  accessModes: 
    - ReadWriteOnce
  storageClassName: foundry-longhorn-handler 
  resources:
    requests: 
      storage: 50Gi
